#!/usr/bin/env bash
set -Eeuo pipefail

# Ensure the ROS Master location is defined
export ROS_MASTER_URI=${ROS_MASTER_URI:-http://localhost:11311}

DIR="$(cd "$(dirname "${BASH_SOURCE}")" && pwd)"
MODEL_DIR="$DIR/models/cube_model"
MAT_DIR="$MODEL_DIR/materials/scripts"
TEX_DIR="$MODEL_DIR/materials/textures"
SDF_FILE="$MODEL_DIR/model.sdf"
SDF_GEN_PY="$MAT_DIR/generate_aruco_sdf.py" # The SDF generator script
TEX_GEN_PY="$MAT_DIR/make_aruco_textures.py" # The texture generator script

NAME="${1:-cube1}"
START="${2:-1}"
X="${3:-0}"
Y="${4:-0}"
Z="${5:-0.05}"
YAW="${6:-0}"
DICT="${7:-DICT_4X4_100}"
PX="${8:-512}"

require() { command -v "$1" >/dev/null 2>&1 || { echo "Missing '$1' in PATH"; exit 1; }; }

# --- deps ---
require rosservice
require python3
[[ -f "$SDF_GEN_PY" ]] || { echo "Not found: $SDF_GEN_PY"; exit 1; }
[[ -f "$TEX_GEN_PY" ]] || { echo "Not found: $TEX_GEN_PY"; exit 1; }

mkdir -p "$MAT_DIR" "$TEX_DIR"

# --- generate missing textures on demand ---
IDS=("$START" "$((START+1))" "$((START+2))" "$((START+3))" "$((START+4))")
MISSING=()
for id in "${IDS[@]}"; do
  [[ -f "$TEX_DIR/aruco_${id}.png" ]] || MISSING+=("$id")
done

if (( ${#MISSING[@]} > 0 )); then
  echo "[spawn] generating missing textures via Python for IDs: ${MISSING[*]}"
  python3 "$TEX_GEN_PY" --ids "${MISSING[@]}" --dict "$DICT" --px "$PX" --out "$TEX_DIR"
fi

# ensure blank exists
[[ -f "$TEX_DIR/blank.png" ]] || python3 "$TEX_GEN_PY" --ids "${IDS[0]}" --dict "$DICT" --px "$PX" --out "$TEX_DIR" >/dev/null 2>&1 || true

# --- (re)generate minimal OGRE material entries for these IDs + blank ---
# (This assumes generate_aruco_sdf.py uses standard Ogre names)
cat >"$MAT_DIR/aruco.material" <<EOF
material blank { technique { pass { texture_unit { texture blank.png } } } }
EOF
for id in "${IDS[@]}"; do
cat >>"$MAT_DIR/aruco.material" <<EOF
material aruco_${id} { technique { pass { texture_unit { texture aruco_${id}.png } } } }
EOF
done

# Initialize variables for cleanup trap
tmp="" 
trap 'rm -f "$tmp"' EXIT

# --- wait for Gazebo service ---
# ... (wait loop omitted for brevity, keep yours) ...

# --- build SDF and spawn ---
echo "[spawn] Generating $SDF_FILE..."
python3 "$SDF_GEN_PY" "$NAME" "$START" 0.05 "$DIR" "$X" "$Y" "$Z" "$YAW" > "$SDF_FILE"

# delete if exists (omitted for brevity, keep yours)

echo "[spawn] spawning SDF model $NAME at ($X,$Y,$Z) yaw=$YAW"
rosservice call /gazebo/spawn_sdf_model "model_name: '$NAME'
model_xml: '$(<"$SDF_FILE")'
robot_namespace: ''
initial_pose: {position: {x: 0, y: 0, z: 0}, orientation: {x: 0, y: 0, z: 0, w: 1}}
reference_frame: 'world'"
echo "[spawn] done."


# volume
## models
### cube_model
#### materials
##### scripts
###### aruco.material
##### textures
###### aruco_#.png
##### model.config
##### model.sdf

'''
/volume/
├── spawn_aruco_sdf.sh           (Still lives here to manage spawning)
└── models/
    └── cube_model/
        ├── materials/
        │   ├── scripts/
            ├── generate_aruco_sdf.py  <-- MOVED HERE
        │   │   └── aruco.material (Generated by script)
        │   └── textures/
        │       └── aruco_#.png    (Generated by script)
        ├── model.config         (Needed for `model://` URI)
        └── model.sdf            (Generated by script output or static template)
'''